[project]
name = "payroll-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.133.0",
    "pre-commit>=4.5.1",
    "ruff>=0.15.2",
    "sqlmodel>=0.0.37",
]
